# Generated by claude-sonnet-4-20250514

from typing import Optional
from pydantic import BaseModel, Field


class State(BaseModel):
    topic: Optional[str] = Field(default=None, description="The topic provided when the graph is invoked, used as input for joke generation")
    joke: Optional[str] = Field(default=None, description="The generated joke based on the provided topic, created by the llm_call_generator node and shown to the human")
    funny: Optional[bool] = Field(default=None, description="The evaluation result indicating whether the joke is considered funny or not, determined by the llm_call_evaluator node (randomly judges as funny 50% of the time)")